# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rancherx < Formula
  desc "A kubectl plugin for Rancher"
  homepage "https://torchiaf.github.io/kubectl-rancherx"
  version "0.4.0"
  license "GNU General Public License"
  depends_on :linux

  if Hardware::CPU.intel?
    url "https://github.com/torchiaf/kubectl-rancherx/releases/download/v0.4.0/kubectl-rancherx_Linux_x86_64.tar.gz"
    sha256 "45966f9f60fa5c873a158b47dff8be797366befd5ae3e3df0b70d875030b2879"

    def install
      bin.install "kubectl-rancherx"
    end
  end
end
